# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-15 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20171115_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trips',
            field=models.ManyToManyField(related_name='_user_trips_+', to='login_app.User'),
        ),
    ]
